name: Tweet Bot

on:
  schedule:
    - cron: "47 5 * * *"  # Runs at 11:17 AM IST (5:47 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # ✅ Updated to latest version
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests tweepy wikipedia-api  # ✅ Includes 'requests' package

      - name: Run the Twitter bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python tweet_bot.py
